- name: print the variables
  hosts: web
  vars:
    NAME: "Nagendrababu"
    DESIGNATION: "Sr.DevOps Engineer"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "This is {{NAME}}, working as {{DESIGNATION}}"