- name: "print the vars from files"
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: "printitng the vars"
    ansible.builtin.debug:
      msg: "{{NAGENDRA}}'s {{DESIGNATION}} is working on {{COURSE}}'"