- name: "Print the var from prompt"
  hosts: web
  vars_prompt:
  - name: NAME
    prompt: "Please enter the prompt"
    prinvate: false # value will be visbile in cmd line
  - name: DESIGNATION
    prompt: "please enter the Designation"
    private: false
  tasks:
  - name: "Print the varfrom prompt"
    ansible.builtin.debug:
      msg: "{{NAME}}'s {{DESIGNATION}}"