- name: "create the user expense"
  become: yes
  hosts: local
  connection: local
  tasks:
  - name: "create the  user info"
    ansible.builtin.command: id expense
    register: USER # it will store the output of above ansible.builtin.command
    ignore_errors: true # it will ignore the error and proceed for next task

  - name: "get the user info"
    ansible.builtin.debug:
      msg: "information of the expense user: {{ USER }} " 
  
  - name: "Creating the user"
    ansible.builtin.command: useradd expense
    when: USER.rc  != 0  # return code is 0 for the created users. If user is not existed, then rc is non-zero 

