- name: "create the user expense"
  become: yes
  hosts: local
  connection: local
  tasks:
  - name: "create the  user info"
    ansible.builtin.command: id expense
    register: USER # it will store the output of above ansible.builtin.command
    ignore_errors: true # it will ignore the error and proceed for next task

  - name: "get the user info"
    ansible.builtin.debug:
      msg: "information of the expense user: {{ USER }} " 
  
  - name: "Creating the user"
    ansible.builtin.cmd: id expense
    when: {{ USER.rc }} != 0

