- name: "print the facts"
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print hte facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}" # it will print all the varibales from the ansible node. 