- name: loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: loops are working
    ansible.builtin.debug:
      msg: Hi ! This is {{ item }}
    loop:
    - Nagu
    - Sush
    - shanvi
    - Navisha
  
  - name: install the packages
    ansible.builtin.package:
      name: {{ item }}
      state: present
    loop:
    - nginx
    - mysql
    - openshift
