- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default("DevOps") }}" #If course is not defined, then it will print the default value.