- name: demo on filters/functions
  hosts: local
  connection: local
  vars:
    course: "DevOps with AWS"
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default('DevOps') }}" #If course is not defined, then it will print the default value.

  - name: convert to uppercase
    vars:
      greeting: "Hi This is Nagendrababu"
    ansible.builtin.debug:
      msg: Hello {{ greeting  | upper }} # convert greeting var to uppercase
  
  - name: convert to lower case
    vars:
      greeting: Hi This is Sushma
    ansible.builtin.debug:
      msg: Hi {{ greeting | lower }} # convert to lower
  
  - name: convert map to string
    vars:
      nagendra:
        name: "Nagendrababu"
        age: 37
        designation: "sr.Technical Sr.TechnicalLead"
    ansible.builtin.debug:
      msg: "{{ nagendra | dict2items }}"
  
  - name: convert list to map
    vars:
      nagendra:
      - name: nagendra
      - age: 37
      - designation: Sr.TechnicalLead
    ansible.builtin.debug:
      msg: "{{ nagendra | items2dict }}"
      