- name: demo on filters/functions
  hosts: local
  connection: local
  vars:
    course: "DevOps with AWS"
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default('DevOps') }}" #If course is not defined, then it will print the default value.

  - name: convert to uppercase
    var:
      greeting: "Hi This is Nagendrababu"
    ansible.builtin.debug:
      msg: "Hello {{ greeting  | upper }}"