- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: command
    ansible.builtin.command: ls -lrth 
    register: CMD1 # save the output from above command
  
  - name: shell
    ansible.builtin.shell: ps -ef | grep ansible >> /tmp/output.txt
    register : CMD

  - name: print the output of shell
    ansible.builtin.debug:
      msg: " {{ CMD }}"

  - name: print the output of command
    ansible.builtin.debug:
      msg: " {{ CMD1 | to_yaml }} "
      