- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: command
    ansible.builtin.command: ls -lrth 
    register: CMD # save the output from above command
  - name: print the output
    ansible.builtin.debug:
      msg: " {{ CMD | to_yaml }} "
  
  - name: shell
    ansible.builtin.shell: ps -ef | grep ansible >> /tmp/output.txt
    register : CMD
    
  - name: print the output of shell
    ansible.builtin.debug:
      msg: " {{ CMD }}"
      