- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: command
    ansible.builtin.command: ls -lrth
    register: cmd
  - name: print the output
    ansible.builtin.debug:
      msg: cmd 