- name: creating the user
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: creating hte user
    ansible.builtin.command: id nagendra
    register: USER
    ignore_errors: true
  
  - name: get the user information
    ansible.builtin.debug:
      msg: "information of the user" {{ USER.rc }}
  # - name: creating hte user
  #   ansible.builtin.command: adduser nagendra
  #   when: "{{ USER.rc }}" != 0
      